# Tic-tac-toe minmax algorithm with search limits
We will demonstrate the minmax algorithm on a game played on a 3x3 game board.

In [4]:
import numpy as np

The State class captures the current state of the game.
* **Attributes**
    * gameplan - 3x3 game board with values 0 to 2
    * player - the player who is currently on the turn
    * current_player - the player will analyze the game and keep track of possible new states. Players take turns, so the new state should be viewed from the perspective of the opposing player. the player who is on the turn in the current state when searching the state space
    * depth - the depth of the analyzed state
    * max_depth - how many moves ahead the maximum is looking. If depth = max_depth, I don't analyze the game any further.

* **Methods**
    * terminal_test - method returns information whether the current state is final or not. If it is, it returns the winner.
    * utility - the method tries to evaluate the current state from the player's perspective. In the basic version, it only distinguishes whether the player wins, doesn't win or the move doesn't lead to the end of the game.
    * possible_actions - the method returns a list of possible moves. In the case of biscuits, this will be the coordinates of the playing area where the playing stone can be placed.
    * expand - this method takes the current state and action definition (the coordinates where to place the die) and creates a new game state.
    * minmax - custom implementation of the minmax algorithm
    * next_current_player - returns the opponent to the current_player variable
    * next_player - returns the opponents to the player variable    

In [ ]:
class State:
    """ Capturing the state of the game
    gameplan - two-dimensional 3x3 array
             - 0 - empty array
             - 1 - X
             - 2 - O
    """

    generated = 0

    def __init__(self, gameplan, player, current_player=None, depth=0, max_depth=3):
        self.gameplan = gameplan
        self.player = player
        if current_player is None:
            self.current_player = player
        else:
            self.current_player = current_player
        self.depth = depth
        self.max_depth = max_depth
        
        State.generated += 1

    def terminal_test(self):
        

        # horizontal and vertical triplets
        for i in range(3):
            if np.array_equal(self.gameplan[i], [1, 1, 1]):
                return 1
            if np.array_equal(self.gameplan[i], [2, 2, 2]):
                return 2
            if np.array_equal(self.gameplan[:, i], [1, 1, 1]):
                return 1
            if np.array_equal(self.gameplan[:, i], [2, 2, 2]):
                return 2

        # diagonals
        if np.array_equal(self.gameplan.diagonal(), [1, 1, 1]):
            return 1
        if np.array_equal(self.gameplan.diagonal(), [2, 2, 2]):
            return 2
        if np.array_equal(np.fliplr(self.gameplan).diagonal(), [1, 1, 1]):
            return 1
        if np.array_equal(np.fliplr(self.gameplan).diagonal(), [2, 2, 2]):
            return 2

        return 0

    def utility(self, result):
        if result == 0:
            return 0
        elif result == self.player:
            return 1
        else:
            return -1

    def possible_actions(self):
        possible_actions = []
        # Finding empty playing fields
        for i in range(3):
            for j in range(3):
                if self.gameplan[i][j] == 0:
                    possible_actions.append((i, j))
        return possible_actions

    def expand(self, select_action):
        if select_action[0] not in range(3):
            return None
        if select_action[1] not in range(3):
            return None

        # playing field must be clear
        if self.gameplan[select_action[0], select_action[1]] != 0:
            return None
        
        new_array = np.copy(self.gameplan)
        new_array[select_action[0], select_action[1]] = self.current_player
        return State(new_array, 
                     self.player, 
                     self.next_current_player(), 
                     self.depth + 1, 
                     max_depth=self.max_depth)
        

    def minmax(self, strategy="max"):
        """"
        The method selects the one that matches the strategy from the possible actions for the given game state

        stategy 
        """
        
        # checking the state of the game.
        result = self.terminal_test()
        if result != 0:            
            return self.utility(result), action
        

        # initialization of values for each strategy
        if strategy == "max":
            selected_utilization_value = float('-inf')
            next_strategy = "min"
        else:
            selected_utilization_value = float('inf')
            next_strategy = "max"

        actions = self.possible_actions()

        selected_action = actions[0]

        for action in actions:

            expanded_state = self.expand(action)

            #  check the game ending for expanded state
            result = expanded_state.terminal_test()

            if result != 0:
                return expanded_state.utility(result), action
            else:
                if len(expanded_state.possible_actions()) == 0:
                    utilization = 0
                else:
                    utilization, _ = expanded_state.minmax(next_strategy)

                if utilization > selected_utilization_value and strategy == "max":
                    selected_utilization_value = utilization
                    selected_action = action
                elif utilization < selected_utilization_value and strategy == "min":
                    selected_utilization_value = utilization
                    selected_action = action

        return selected_utilization_value, selected_action

    def next_current_player(self):
        return 3 - self.current_player

    def next_player(self):
        return 3 - self.player

# Task
- Add a constraint to the algorithm to limit the maximum search depth.
- Try different search depth constraints.
- Observe how the times and numbers of generated states change
- Are the game results changing?

You need to implement a limitation on the # !!! todo

In [6]:

state = State(gameplan=np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]]),
              player=1, max_depth=2)
while True:
    game_result = state.terminal_test()
    if game_result != 0:
        print(f"Winner is {game_result} ")
        break

    if len(state.possible_actions()) == 0:
        print("Drawn")
        break

    print(f"=====================\nPlayer {state.player}")
    _, player_action = state.minmax("max")
    print(f"Select action: {player_action}")
    state = state.expand(player_action)
    print(state.gameplan)
    print(f"Generated states {State.generated}.")
    State.generated = 0

    state.player = state.next_player()

Player 1
Select action: (0, 0)
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Generated states 269175.
Player 2
Select action: (1, 1)
[[1 0 0]
 [0 2 0]
 [0 0 0]]
Generated states 26853.
Player 1
Select action: (0, 1)
[[1 1 0]
 [0 2 0]
 [0 0 0]]
Generated states 2425.
Player 2
Select action: (0, 2)
[[1 1 2]
 [0 2 0]
 [0 0 0]]
Generated states 77.
Player 1
Select action: (2, 0)
[[1 1 2]
 [0 2 0]
 [1 0 0]]
Generated states 66.
Player 2
Select action: (1, 0)
[[1 1 2]
 [2 2 0]
 [1 0 0]]
Generated states 17.
Player 1
Select action: (1, 2)
[[1 1 2]
 [2 2 1]
 [1 0 0]]
Generated states 10.
Player 2
Select action: (2, 1)
[[1 1 2]
 [2 2 1]
 [1 2 0]]
Generated states 5.
Player 1
Select action: (2, 2)
[[1 1 2]
 [2 2 1]
 [1 2 1]]
Generated states 2.
Drawn
